---
title: "multicollinearity"
output: github_document
---

```{r}
library(tidyverse)
library(lubridate)
library(caret)
library(feather)
library(reshape2)
```

```{r}
# See README for how to create feather files.
df <- read_feather("../data/train.feather")

#' Set upper triangle of matrix to NA
#'
#' @param corr_matrix A matrix
#'
#' @return Matrix with upper triangle set to NA
upper_tri_na <- function(corr_matrix) {
  corr_matrix[upper.tri(corr_matrix)] <- NA
  corr_matrix
}

# Create dataframe for correlation matrix plot
corr_df <- df %>% 
  select(total_volume, 
         PLU_4046, 
         PLU_4225, 
         PLU_4770, 
         total_bags, 
         small_bags, 
         large_bags, 
         xlarge_bags, 
         #type, 
         #year, 
         #region, 
         #month
         ) %>% 
  cor %>% 
  upper_tri_na %>% 
  melt(na.rm = TRUE) %>% 
  mutate(value = round(value, 2))

ggplot(corr_df) + 
  geom_tile(aes(Var1, Var2, fill = value)) +
  geom_text(aes(Var1, Var2, label = value), color = "black", size = 4) +
  scale_fill_distiller(palette="GnBu", direction=1) +
  labs(title="Correlation Matrix",
       subtitle = "Avocado Data",
       fill="Pearson's\nCorrelation") +
  coord_fixed() +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major = element_blank(),
        legend.justification = c(1, 0),
        legend.position = c(0.55, 0.7),
        legend.direction = "horizontal") +
  guides(fill = guide_colorbar(barwidth = 7, 
                               barheight = 1,
                               title.position = "top", 
                               title.hjust = 0.5))
```
